#!/bin/bash
for numc in $(ls -1 $1/*numc*.root); do 
  tailstub=${numc##*oa_nt_beam_} 
  rsr=${tailstub%%_*}
  if [ ! -e $1/*${rsr}*anal*.root ]; then
    RUNNUM=${rsr%%-*}
    SRUNNUM=${rsr##*-}
    echo "$((10#${RUNNUM})).$((10#${SRUNNUM}))"
  fi
done
