#!/bin/bash

for log in $(ls -1 $1/*.log); do
  LOGF=${log##*/}
  JOBID=${LOGF%%.*}
  TAILSTUB=${LOGF#*.}
  TASKID=${TAILSTUB%%.*}
  RUNTAG=$(printf %08i ${JOBID})
  SRUNTAG=$(printf %04i ${TASKID})
  if [ ! -e $1/*${RUNTAG}-${SRUNTAG}*numc*.root ]; then
    echo "${JOBID}.${TASKID}"
  fi
done

