#!/bin/bash

ROOT=${1}

while IFS= read -r line ; do
  RUNNUM=${line%%.*}
  SRUNNUM=${line##*.}
  f=${ROOT}/${line}.log
  if [ ! -e ${f} ]; then
    f=${ROOT}/${RUNNUM}.0.log
  fi

  tail ${f} | grep --silent "Some of the step tasks have been OOM Killed."
  FOUND=${PIPESTATUS[1]}
  if [ ${FOUND} -eq 1 ]; then
    echo "${RUNNUM}.${SRUNNUM}"
  fi

done <<< "$(find_failed_sim2ev ${ROOT})"
