#!/bin/bash

ROOT=${1}
shift

while [ ${#} -gt 0 ]; do
  RUNNUM=${1%%.*}
  SRUNNUM=${1##*.}
  f=${ROOT}/${1}.log
  if [ ! -e ${f} ]; then
    f=${ROOT}/${RUNNUM}.0.log
  fi
  echo ">>>>>>>>>>>>>>>>${f}>>>>>>>>>>>>>>>"
  tail ${f}
  shift;
  echo "<<<<<<<<<<<<<<<<${f}<<<<<<<<<<<<<<<"
done
