#!/bin/bash

#SBATCH -p scarf
#SBATCH -n 1
#SBATCH -o %J.log
#SBATCH -J nd280job

if [ -z "${SLURM_JOB_ACCOUNT}" ]; then
	SLURM_JOB_ACCOUNT=ppd
	SLURM_JOB_NAME=test
	SLURM_JOB_ID=22072207
	SLURM_LOCALID=123
fi

JOB_SCRIPT=$(readlink -f ${1})
echo "JOB SCRIPT: ${1} resolved to: ${JOB_SCRIPT}"
if [ ! -e ${JOB_SCRIPT} ] || [ -z "${JOB_SCRIPT}" ]; then
  echo "Failed to find JOB SCRIPT: ${1}. Cannot continue"
  return 1
fi
shift;

# try and make array and multistep job output look equivalent
if [ ! -z "${SLURM_ARRAY_TASK_ID}" ]; then
  export ND280_JOB_ID=${SLURM_ARRAY_JOB_ID}
  OUTPUT_PATTERN="%A.%a.log"
else
  export ND280_JOB_ID=${SLURM_JOB_ID}
  OUTPUT_PATTERN="%j.%t.log"
fi

mkdir -p ${ND280_JOB_ID}; cd ${ND280_JOB_ID}

export SUBDIR=$(pwd)

if [ -e /scratch ]; then
  export JOBDIR=/scratch/picker24/${SLURM_JOB_ACCOUNT}_${SLURM_JOB_NAME}_${SLURM_JOB_ID}
else
  export JOBDIR=/tmp/${SLURM_JOB_ACCOUNT}_${SLURM_JOB_NAME}_${SLURM_JOB_ID}
fi

export SCRIPT_ROOT=$MYWORK4/nd280/scripts

SECONDS=0
echo "Job start: $(date)"

set -x
mkdir -p ${JOBDIR}
set +x

srun -o "${OUTPUT_PATTERN}" ${SCRIPT_ROOT}/env/apptainer.run ${SCRIPT_ROOT}/batch/task_wrapper ${JOB_SCRIPT} ${@}

set -x
ls ${JOBDIR}/*
rm -r ${JOBDIR}
echo "Job end: $(date)"
echo "Job elapsed: $(echo "${SECONDS} / 60" | bc)m $(echo "${SECONDS} % 60" | bc)s"
