#!/bin/bash

RUNNUM=${1}
SRUNNUM=${2}
NEUT_CARD=${3}
INT_REGION=${4}
FLUX_REGION=${5}
FLUX_FILE=${6}
MAXINT_FILE=${7}
POT=${8}

COMMENT=""
if [ ${#} -gt 8 ]; then
  COMMENT=${9}
fi

SEEDS=( $(${SCRIPT_ROOT}/batch/utils/rseeds.py 65534 3) )
NEUT_SEED1=${SEEDS[0]}
NEUT_SEED2=${SEEDS[1]}
NEUT_SEED3=${SEEDS[2]}

cat ${SCRIPT_ROOT}/batch/runND280cfg/numc.cfg.in \
	| sed "s:__NEUT_CARD__:${NEUT_CARD}:g" \
	| sed "s:__INT_REGION__:${INT_REGION}:g" \
	| sed "s:__FLUX_REGION__:${FLUX_REGION}:g" \
	| sed "s:__FLUX_FILE__:${FLUX_FILE}:g" \
	| sed "s:__MAXINT_FILE__:${MAXINT_FILE}:g" \
	| sed "s:__NEUT_SEED1__:${NEUT_SEED1}:g" \
	| sed "s:__NEUT_SEED2__:${NEUT_SEED2}:g" \
	| sed "s:__NEUT_SEED3__:${NEUT_SEED3}:g" \
	| sed "s:__POT__:${POT}:g" \
	| sed "s:__RUNNUM__:${RUNNUM}:g" \
	| sed "s:__SRUNNUM__:${SRUNNUM}:g" \
	| sed "s:__COMMENT__:${COMMENT}:g" \
	> numc.cfg

echo "=====>>numc.cfg====="
cat numc.cfg
echo "=====<<numc.cfg====="

runND280 -c numc.cfg -t $(pwd)

if [ ! -z "${SUBDIR}" ]; then
  cp $(${SCRIPT_ROOT}/batch/utils/findnumc) ${SUBDIR}/
fi
