#!/bin/bash

NEUT_CARD=${1}
INFILE=${2}
MAXINT_FILE=${3}
T2K_RUN=${4}

if [ "${INFILE##*.}" == "root" ]; then
  NUMC_FILE=${INFILE}
else
  NUMC_FILE_LOC=$(cat ${INFILE} | head -${ND280_TASK_ID} | tail -1)
  cp ${NUMC_FILE_LOC} ./
  NUMC_FILE=${NUMC_FILE_LOC##*/}
fi

echo "Attempting to run with NUMC_FILE=${NUMC_FILE}"

if [ -z "${NUMC_FILE}" ]; then
  echo "No input NUMC file passed."
  return 1
fi

SEEDS=( $(${SCRIPT_ROOT}/batch/utils/rseeds.py 65534 5) )
NEUT_SEED1=${SEEDS[0]}
NEUT_SEED2=${SEEDS[1]}
NEUT_SEED3=${SEEDS[2]}
G4_SEED=${SEEDS[3]}
ELECSIM_SEED=${SEEDS[4]}

${SCRIPT_ROOT}/utils/pps.py -i ${MAXINT_FILE} -r ${T2K_RUN} > pps.dat
PPS=$(head -1 pps.dat)
IPS=$(tail -1 pps.dat)
rm pps.dat

cat ${SCRIPT_ROOT}/batch/runND280cfg/sim2evana.cfg.in \
	| sed "s:__NEUT_CARD__:${NEUT_CARD}:g" \
	| sed "s:__NUMC_FILE__:${NUMC_FILE}:g" \
	| sed "s:__NEUT_SEED1__:${NEUT_SEED1}:g" \
	| sed "s:__NEUT_SEED2__:${NEUT_SEED2}:g" \
	| sed "s:__NEUT_SEED3__:${NEUT_SEED3}:g" \
	| sed "s:__MAXINT_FILE__:${MAXINT_FILE}:g" \
	| sed "s:__G4_SEED__:${G4_SEED}:g" \
	| sed "s:__ELECSIM_SEED__:${ELECSIM_SEED}:g" \
	| sed "s:__IPS__:${IPS}:g" \
	| sed "s:__PPS__:${PPS}:g" \
	> sim2evana.cfg

echo "=====>>sim2evana.cfg====="
cat sim2evana.cfg
echo "=====<<sim2evana.cfg====="

runND280 -c sim2evana.cfg -t $(pwd)
EXIT_STATUS=$?

echo "runND280 exit status: ${EXIT_STATUS}"

#copy out
if [ ! -z "${SUBDIR}" ]; then
  
  if [ ${EXIT_STATUS} -eq 0 ]; then
    cp *anal*.root ${SUBDIR}/
  fi

  if [ ! -z "${KEEP_G4MAC}" ] || [ ${EXIT_STATUS} -ne 0 ]; then
    cp *g4mc*.mac ${SUBDIR}/
  fi

  if [ ! -z "${KEEP_ELMC}" ] || [ ${EXIT_STATUS} -ne 0 ]; then
    cp *elmc*.root ${SUBDIR}/
  fi

  if [ ! -z "${KEEP_RECO}" ] || [ ${EXIT_STATUS} -ne 0 ]; then
    cp *reco*.root ${SUBDIR}/
  fi
fi
